paritytech/zombienet-sdk

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_report.yaml
.gitignore

- Add gitignore
- Add feature template
- Add bug template
- Add CODEOWNERS

Add repo setup

---

Cargo.toml
crates/orchestrator/.gitignore
crates/orchestrator/Cargo.toml
crates/orchestrator/src/lib.rs
crates/provider/.gitignore
crates/provider/Cargo.toml
crates/provider/src/lib.rs
crates/support/.gitignore
crates/test-runner/.gitignore
crates/test-runner/Cargo.toml
crates/test-runner/src/lib.rs

Add all crates for initial setup of workspaces

---

.github/workflows/ci.yml

Close https://github.com/paritytech/zombienet-sdk/issues/66

feat: added cargo fmt to pipeline

---

crates/provider/src/errors.rs
crates/provider/src/lib.rs
crates/provider/src/native.rs
crates/provider/src/shared/constants.rs
crates/support/src/fs/mock.rs

Small refactor, with some docs and tests.

small refactor

---

crates/provider/Cargo.toml
crates/provider/src/lib.rs
crates/provider/src/native.rs
crates/provider/src/shared/types.rs

- Fix warnings;
- Implement pause, resume, restart

Implement pause, resume, restart

---

Cargo.toml
crates/examples/Cargo.toml
crates/examples/examples/small_network.rs
crates/examples/examples/small_network_with_default.rs

Add `examples` to use with the `configuration` crate.

add examples crate

---

crates/orchestrator/src/generators/chain_spec.rs
crates/orchestrator/src/lib.rs
crates/orchestrator/src/network_spec.rs
crates/provider/src/native.rs

Small cleanup to looks betters.

chores: cleanups and todos

---

crates/orchestrator/src/generators/chain_spec.rs

Call `add_collator_selection` to customize `invulnerables` for both session and aura keys.
cc @pgherveou

fix(orchestrator): customize invulnerables

---

crates/orchestrator/src/generators/chain_spec.rs
crates/orchestrator/testing/rococo-local-plain.json

- wire `add_hrmp_channels` to customize relaychain spec.

feat: add `add_hrmp_channels` fn to customize relaychain

---

.github/workflows/ci.yml

chore(ci): add cache to workflows

---

.gitlab-ci.yaml
crates/orchestrator/src/network.rs
crates/orchestrator/src/network/node.rs
crates/provider/src/kubernetes/client.rs
crates/provider/src/kubernetes/namespace.rs
crates/provider/src/lib.rs
crates/sdk/Cargo.toml
crates/sdk/src/lib.rs
crates/sdk/tests/smoke.rs

This is a very simple gitlab CI manifest to just check the tag on this pipeline schedule it on Zombienet k8s runner and is the SA inject to the runners in privileged enough to run command within the cluster or not

chore: gitlab runner test for new repo

---

.gitlab-ci.yml

Add smoke test for k8s provider.

chore(ci): add smoke test

---

.gitlab-ci.yml
crates/orchestrator/src/spawner.rs
crates/provider/src/kubernetes/client.rs
crates/provider/src/kubernetes/namespace.rs
crates/provider/src/kubernetes/node.rs
crates/provider/src/lib.rs
crates/provider/src/native/node.rs
crates/sdk/src/lib.rs

add cmd to RunCommandError

---

.github/workflows/ci.yml
.gitlab-ci.yml
crates/configuration/src/network.rs
crates/provider/src/kubernetes/namespace.rs
crates/provider/src/kubernetes/scripts/zombie-wrapper.sh
crates/provider/src/shared/helpers.rs
crates/sdk/tests/smoke.rs

- Add clean disk space action.

chore(ci): fix coverage

---

crates/provider/src/kubernetes/client.rs
crates/provider/src/kubernetes/namespace.rs

- Remove workaround on temp  node issues. (fixed in wrapper).

fix(orchestrator): remove workaround on temp nodes

---

crates/orchestrator/src/network/node.rs

Enables using an arbitrary predicate to assert on metrics instead of just equality, which may be brittle because of casting everything to a floating-point type.
Usage example:
```rust
if node.assert_with("block_height{status=\"best\"}", |bh| bh > 10).await? {
println!("Block height is over 10");
}
```

Generalize metric assertions

---

crates/configuration/src/global_settings.rs
crates/configuration/src/lib.rs
crates/configuration/src/network.rs
crates/configuration/src/parachain.rs

- Review docs of the configuration crate and exposed entry configuration with an example how to use the NetworkConfigBuilder

docs: review/update configuration crate doc

---

crates/orchestrator/src/network/node.rs
crates/provider/src/kubernetes/node.rs

Add:
- logs methods in NetworkNode

feat(orchestrator): expose logs methods for NetworkNodes

---

crates/provider/src/native/node.rs

fix #210 
Also fix the log cmd string.
cc @michalkucharczyk , thanks!!

fix: leaking env to node process and log cmd (native provider)

---

Cargo.toml
crates/examples/Cargo.toml
crates/orchestrator/Cargo.toml
crates/orchestrator/src/lib.rs
crates/orchestrator/src/network/node.rs
crates/orchestrator/src/pjs_helper.rs
crates/orchestrator/src/shared/types.rs
crates/sdk/Cargo.toml
crates/sdk/src/lib.rs

cc @sandreim thanks for the suggestion :)

feat: put `pjs-rs` behind a feature-gate

---

Cargo.toml

- pjs-rs behind feature gate
- Docker fixes

bump versions for release `v0.2.3`

---

crates/orchestrator/src/lib.rs

Simplify logic and:
- Ensure we are passing the bootnodes in both relay and parachains
- Ensure we add the bootnodes to chain-spec file.
cc: @patriciobcs

fix: bootnodes logic

---

Cargo.toml

chore: bump versions for release

---

crates/orchestrator/src/lib.rs

Fix: inject chain spec para

---

crates/orchestrator/src/network/node.rs
crates/sdk/tests/smoke.rs
crates/support/Cargo.toml
crates/support/src/net.rs

- Add `wait` methods for subxt client.

feat: add wat methods for `subxt` client

---

Cargo.toml
crates/orchestrator/src/network/parachain.rs

cc: @s0me0ne-unkn0wn  (Thanks for report 🙌 )

chore: bump `subxt` version

---

Cargo.toml
crates/orchestrator/src/network/node.rs

Add: 
- Bump subxt version
- Change visibility for internal crates

chore: bump versions for release `0.2.6`

---

crates/provider/src/kubernetes/client.rs

- Add: Tracing for port-fwd in k8s.

feat(k8s): add tracing for port-fwd

---

Cargo.toml

bump versions to release `0.2.8`

---

crates/orchestrator/src/network/relaychain.rs
crates/orchestrator/src/tx_helper/runtime_upgrade.rs

[fix] Use node as arg for upgrade

---

Cargo.toml

- Fixes
- Upgrade heleper for CI.

bump versions for release `0.2.12`

---

Cargo.toml

Fix
- CI using native provider

bump versions for release `0.2.13`

---

crates/orchestrator/src/generators/chain_spec.rs

Fix #250, follow same _impl_ of `v1`

Fix grandpa keys in chain-spec

---

crates/examples/examples/para_upgrade.rs
crates/orchestrator/src/network.rs
crates/orchestrator/src/network/chain_upgrade.rs
crates/orchestrator/src/network/parachain.rs
crates/orchestrator/src/network/relaychain.rs
crates/sdk/src/lib.rs

- Added
- ChainUpgrade trait, implemented for both relay and parachain.
- Add example of parachain upgrade.
cc @ordian

Feat upgrade runtime for parachains

---

Cargo.toml

Fix `fn nodes()` visibility (#277)

bump version for release `v0.2.17`

---

crates/configuration/src/shared/types.rs
crates/examples/Cargo.toml
crates/examples/examples/add_para.rs
crates/examples/examples/para_upgrade.rs
crates/examples/examples/pjs.rs
crates/examples/examples/simple_network_example.rs
crates/orchestrator/src/generators/command.rs
crates/orchestrator/src/network/chain_upgrade.rs
crates/sdk/Cargo.toml
crates/sdk/src/lib.rs

re-export our version of subxt /signer
cc: @pgherveou

re-export subxt and signer

---

crates/provider/src/kubernetes/node.rs

Fix race condition (overriding files in fileserver).

check hash and retry in 'sendFiles'

---

crates/orchestrator/src/generators/chain_spec.rs

Add logic for customize the `staking` genesis config  at relaychain spec.
cc: @ordian

fix(orchestrator): customize staking for relay

---

crates/orchestrator/src/generators/command.rs
crates/orchestrator/src/spawner.rs

fix(orchestrator): Add logic to ensure full node prometheus port is unique

---

.gitlab-ci.yml
crates/orchestrator/src/lib.rs
crates/orchestrator/src/spawner.rs

echo of https://github.com/paritytech/zombienet/pull/1968

add papi link

---

Cargo.toml

bump versions to release `v0.2.27`

---

Cargo.toml
crates/cli/Cargo.toml
crates/cli/src/main.rs
crates/sdk/src/environment.rs

add cli support for spawn

---

crates/configuration/src/parachain.rs
crates/orchestrator/src/generators/command.rs
crates/orchestrator/src/lib.rs
crates/orchestrator/src/network_spec/parachain.rs

This is needed for testing of https://github.com/paritytech/polkadot-sdk/issues/1825.

Allow spawning parachains without bootnodes

---

crates/orchestrator/src/shared/constants.rs
crates/orchestrator/src/spawner.rs

display prometheus port for collator full-node

---

crates/examples/examples/register_para.rs
crates/orchestrator/src/network.rs
crates/orchestrator/src/network/node.rs

Add:
- `register_parachain()` to the Network struct
Useful when manually registering a parachain in the network
- `multiaddr()`
https://github.com/paritytech/zombienet-sdk/issues/330

Add some useful methods

---

crates/provider/src/kubernetes/static-configs/namespace-network-policy.yaml

Used in our `CI`
cc: @lrubasze

allow ingress from `arc-runners`

---

Cargo.toml

bump versions for release `v0.3.1`

---

crates/orchestrator/src/lib.rs

This info could be used later in CI to construct the links to grafana.
thx!

add info to zombie.json

---

crates/configuration/src/network.rs
crates/configuration/src/parachain.rs
crates/configuration/src/shared/helpers.rs
crates/configuration/src/shared/types.rs
crates/examples/examples/two_paras_same_id.rs
crates/orchestrator/src/network_spec.rs
crates/orchestrator/src/network_spec/parachain.rs

allow to set two paras with the same id

---

crates/configuration/src/global_settings.rs
crates/configuration/src/utils.rs
crates/configuration/testing/snapshots/0000-small-network.toml
crates/configuration/testing/snapshots/0001-big-network.toml
crates/configuration/testing/snapshots/0002-overridden-defaults.toml
crates/configuration/testing/snapshots/0003-small-network_w_parachain.toml
crates/provider/src/kubernetes/client.rs

k8s, move spawn timeout to 10m

---

Cargo.toml

bump version for release `v0.3.4`

---

Cargo.lock
Cargo.toml

- Make `WithRelaychain` public

bump versions for release `v0.3.5`

---

crates/configuration/src/network.rs
crates/configuration/src/relaychain.rs
crates/configuration/src/shared/helpers.rs
crates/configuration/src/shared/resources.rs
crates/configuration/src/shared/types.rs
crates/examples/examples/add_para.rs
crates/examples/examples/pjs.rs
crates/examples/examples/register_para.rs
crates/orchestrator/src/generators/chain_spec.rs
crates/orchestrator/src/generators/command.rs
crates/orchestrator/src/generators/key.rs
crates/orchestrator/src/lib.rs
crates/orchestrator/src/network.rs
crates/orchestrator/src/network/parachain.rs
crates/orchestrator/src/network_spec/node.rs
crates/orchestrator/src/network_spec/parachain.rs
crates/orchestrator/src/network_spec/relaychain.rs
crates/orchestrator/src/spawner.rs
crates/prom-metrics-parser/src/lib.rs
crates/provider/src/docker/node.rs
crates/provider/src/kubernetes/client.rs
crates/provider/src/kubernetes/node.rs
crates/provider/src/native/node.rs
crates/sdk/tests/smoke-native.rs
crates/sdk/tests/smoke.rs
crates/support/src/replacer.rs

This PR is supposed to fix https://github.com/paritytech/zombienet-sdk/issues/367
It makes sure all ports being used are parked during NodeSpec generation.
cc: @pepoviola

Fix port assignment

---

Cargo.lock
Cargo.toml
crates/orchestrator/Cargo.toml
crates/orchestrator/src/network/node.rs

fix #366 
Change regex crate (use fancy regex) to support `lookahead`.
thx!

change regex crate to support `lookahead`

---

.github/workflows/ci_integration.yml
Cargo.lock
Cargo.toml
crates/orchestrator/src/tx_helper/client.rs

bump subxt version

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/main.rs

fix #385 
The error will display something like:
```
Error:
🧟 One of the nodes crashed, collator01: Timeout (5), waiting for metric process_start_time_seconds pass the predicate
```

Cli detect node crash

---

crates/provider/src/kubernetes/static-configs/namespace-network-policy.yaml
crates/sdk/tests/smoke.rs

change `ns` name for new cluster

---

crates/orchestrator/src/generators/chain_spec.rs

Skip the clear of stakers when customizing parachain

---

.github/workflows/release.yml

Basic github workflow for building and releasing zombie-cli
