- crates/configuration/src/parachain.rs
- crates/configuration/src/relaychain.rs
- crates/configuration/src/shared/node.rs
We want the user to be able to set a default command on the relaychain and to override it, to make it type safe, using a Either type with both possible options and a further step of validation to ensure the user defined a command on the node, here a code example with a schema showing what we want to achieve:
> Simplify the node builder to allow default_command

- .github/workflows/ci.yml
- crates/configuration/src/network.rs
- crates/configuration/src/parachain.rs
- crates/configuration/src/relaychain.rs
> Add code coverage check in each pr

- crates/configuration/src/global_settings.rs
- crates/configuration/src/hrmp_channel.rs
- crates/configuration/src/network.rs
- crates/configuration/src/parachain.rs
- crates/configuration/src/relaychain.rs
- crates/configuration/src/shared/node.rs
- crates/support/src/fs/local_file.rs
Remove all `#[derive(Debug)]` from codebase
(Fixes a lot of the coverage report)
> Remove #[derive(Debug)]

- crates/examples/examples/small_network_with_default.rs
- crates/orchestrator/Cargo.toml
- crates/orchestrator/src/network.rs
- crates/orchestrator/src/network/node.rs
- crates/orchestrator/src/spawner.rs
Add methods to NetworkNode:
- pause
- resume
- restart
- reports (get metrics from prometheus)
- assert (basic implementation, we need to add the cmp logic).
Todo: add test when we have the processManager mock
> feat: add node methods for actions and metrics

- crates/examples/examples/small_network_with_default.rs
- crates/orchestrator/src/lib.rs
- crates/orchestrator/src/network.rs
- crates/orchestrator/src/network_helper.rs
- crates/orchestrator/src/network_helper/verifier.rs
- crates/orchestrator/src/spawner.rs
- crates/orchestrator/src/tx_helper.rs
- crates/orchestrator/src/tx_helper/register_para.rs
- crates/orchestrator/src/tx_helper/validator_actions.rs
Add the verifier logic to ensure readiness of the nodes and remove all the `sleeps` in the current examples.
Some todos to make in follow up prs.
> feat: add verifier to check readiness

- crates/orchestrator/src/lib.rs
Register the parachains (that aren't included in the genesis) after we run the verifier and remove the need for using sleep.
Thx!
> Register paras after verify the nodes are running, remove sleep

- Cargo.toml
- crates/examples/examples/simple_network_example.rs
- crates/examples/examples/small_network.rs
- crates/examples/examples/small_network_with_default.rs
- crates/examples/examples/small_network_with_para.rs
- crates/orchestrator/src/lib.rs
- crates/orchestrator/src/network.rs
- crates/provider/src/lib.rs
- crates/sdk/Cargo.toml
- crates/sdk/src/lib.rs
Following up on take 1 https://github.com/paritytech/zombienet-sdk/pull/124
Apart from better logs, I realize that one of the only thing missing now for us to start consuming this project  is a top level package available (with it's dependencies) on crates.io. This PR serves mainly as a discussion point to get there.
It would be great if we could publish an early version (0.0.1?) on crates.io so that we can start using this asap.
> Expose Top level API through zombienet-sdk crate

- crates/orchestrator/src/generators/chain_spec.rs
- crates/orchestrator/src/lib.rs
- crates/orchestrator/src/spawner.rs
- crates/provider/src/lib.rs
- crates/provider/src/native/namespace.rs
- crates/provider/src/native/node.rs
- crates/provider/src/shared/types.rs
Fix parachain spec filename (local) to use when we spawn collators. Also, adding `Context` to spawner to improve error reporting.
cc @pgherveou
> Fix: paras spec file name

- Cargo.toml
- crates/examples/Cargo.toml
- crates/examples/examples/simple_network_example.rs
- crates/examples/examples/small_network_with_default.rs
- crates/examples/examples/small_network_with_para.rs
- crates/orchestrator/src/generators/chain_spec.rs
- crates/orchestrator/src/lib.rs
- crates/orchestrator/src/network.rs
- crates/orchestrator/src/network/node.rs
- crates/orchestrator/src/network/relaychain.rs
- crates/orchestrator/src/network_spec/node.rs
- crates/orchestrator/src/shared.rs
- crates/orchestrator/src/shared/macros.rs
- crates/sdk/src/lib.rs
- Refactor `add_node` to split the logic into add_node (relaychain) / add_collator (parachain).
- Update examples, also adding `tracing_ subscriber` (default)
> Refactor: add node/collator as diff methods

- crates/orchestrator/src/generators/chain_spec.rs
- crates/orchestrator/src/generators/key.rs
Small refactor to use `stash` for validatiors in session keys (relaychain). To use the same behavior we have in v1.
> refactor: add `stash` account to set in session for relaychain validators

- crates/configuration/src/shared/types.rs
- crates/orchestrator/src/generators/chain_spec.rs
- crates/orchestrator/src/generators/key.rs
- crates/orchestrator/src/network_spec/node.rs
- crates/orchestrator/src/shared/types.rs
- Add always the `zombie` account to balances in the relaychain.
- For each node add `sr` and `sr_stash` to balances.
- Test for `add_balances`
> feat(orchestrator): add `zombie` account to balances and use also `stash` for nodes

- Cargo.toml
- crates/examples/Cargo.toml
- crates/examples/examples/pjs.rs
- crates/examples/examples/pjs_transfer.js
- crates/orchestrator/Cargo.toml
- crates/orchestrator/src/lib.rs
- crates/orchestrator/src/network/node.rs
- crates/orchestrator/src/shared/types.rs
- crates/sdk/src/lib.rs
- Add `pjs-rs` support and mimic the [javascript](https://polkadot.js.org/apps/#/js) tab from polkadot.js apps/
- Allow to use an external file or just an string with the `js/ts` code,
TODO: We should implement integration tests for this feature.
> feat: Add `pjs-rs` calls for `Network::Node`

- crates/examples/examples/pjs.rs
> get manifest_dir from env

- crates/configuration/src/lib.rs
- crates/configuration/src/network.rs
- crates/configuration/src/parachain.rs
- crates/configuration/src/shared/node.rs
- crates/examples/Cargo.toml
- crates/examples/examples/add_para.rs
- crates/orchestrator/src/generators/chain_spec.rs
- crates/orchestrator/src/lib.rs
- crates/orchestrator/src/network.rs
- crates/orchestrator/src/network/parachain.rs
- crates/orchestrator/src/network_spec/parachain.rs
This pr make possible to add a new parachain to a running network (see `add_para.rs` example), for that we allow to create a new parachain config (using the same builder but in a different context) like this:
```rs
let para_config = network.para_config_builder()
.with_id(100)
.with_default_command("polkadot-parachain")
.with_collator(|c| {
c.with_name("col-100-1")
})
.build()?;
```
And then deploy that parachain by calling `add_parachain` (the second parameter of the fn allow to use a custom chain-spec for the relaychain).
```rs
network.add_parachain(&para_config, None).await?;
```
// TODO:
> feat: add parachains to a running network

- .github/workflows/ci.yml
- .github/workflows/documentation.yml
- crates/file-server/src/main.rs
We want to add an `startupProbe` setting to the fileserver pod.
> fileserver: add default route to use as health check

- crates/orchestrator/Cargo.toml
Testing with moonbeam and found that the resulting chainspec produced using the `moonbase-local` chain develops the following issue after the generated plain chainspec is updated with the relevant para id:
```
Error: Zombienet(SpawnerError(Provider error
Caused by:
File generation failed: Error: Service(Other("Error parsing spec file: trailing characters at line 25 column 14"))
```
The initial chainspec built from the binary is fine, but once https://github.com/paritytech/zombienet-sdk/blob/e60deb254b5f58e81a55300ae802d5b614f774e5/crates/orchestrator/src/generators/chain_spec.rs#L345-L349 runs the issue occurs, as seen in the the following diff:
```
--- moonbase-local-plain copy.json	2024-02-11 02:51:15
+++ moonbase-local-plain.json	2024-02-11 02:52:24
@@ -11,7 +11,7 @@
"tokenSymbol": …
```
> fix: enable arbitrary_precision for serde_json

- crates/configuration/src/network.rs
Sticking to the `fn` type in the builder pattern doesn't make much sense to me. Consider the following snippet:
```rust
let overrides = json!({ "runtimeGenesis": { "patch": { "configuration": { "config": { "max_pov_size": 5_242_880 } } } } });
let config = NetworkConfigBuilder::new()
.with_relaychain(|r| {
r.with_chain("rococo-local")
.with_genesis_overrides(overrides)
.with_node(|node| node.with_name("alice").with_command("polkadot"))
})
.build();
```
That wouldn't compile, as the `.with_relaychain()` argument closure captures the `overrides` variable and thus cannot be coerced to `fn` anymore. That is, `.with_genesis_overrides` becomes useless unless you want to pass a simple literal there.
On the other hand, all those closures are single-shot, allowing us to make them `FnOnce,` which …
> Fix builder pattern to allow real closures

- crates/orchestrator/src/generators/chain_spec.rs
Fix #173 
We should also add a follow up issue to improve the docs.
cc: @s0me0ne-unkn0wn
> fix(orchestrator): use pointer from 'get_runtime_config_pointer'

- crates/configuration/src/parachain.rs
- crates/orchestrator/src/errors.rs
- crates/orchestrator/src/lib.rs
- crates/provider/src/kubernetes/provider.rs
- crates/provider/src/lib.rs
- crates/provider/src/native/provider.rs
Add small validation, mostly to ensure that the `image` is set in k8s.
fix #143
> Validate spec for provider

- crates/orchestrator/src/generators/command.rs
Concatenating the command line option and its value doesn't really work. The shell treats `--opt val` as a single argument `--opt val` instead of `--opt` `val` and fails to execute. This PR fixes that by separating options from their values.
Error example:
```
error: unexpected argument '--workers-path ~/.cargo/bin/workers-1.6' found
tip: a similar argument exists: '--workers-path'
```
> Fix argument passing

- crates/configuration/src/parachain.rs
- crates/configuration/src/relaychain.rs
- crates/configuration/src/shared/node.rs
A follow-up of #171 with the same motivation.
> Make builders accept `impl FnOnce` instead of `fn`

- .github/workflows/documentation.yml
- Cargo.toml
Small fix 
- exclude the `test-runner` from the workspace (for now)
- Change docs links to point to `sdk`
> fix: comment test-runner and fix docs link

- crates/orchestrator/src/network.rs
based on #190 
cc: @s0me0ne-unkn0wn
> remove hashmap `nodes_by_name`

- crates/orchestrator/src/generators/command.rs
- crates/sdk/tests/smoke.rs
- [k8s] fix `cmd` generator for collators (needs to use exposed ports).
> fix(k8s): collator port assignment to use in cmd

- crates/orchestrator/src/network.rs
- crates/orchestrator/src/network_spec.rs
- crates/sdk/tests/smoke.rs
fix #194 
Add logic to compute the args_output (if needed) for add_node/add_collator.
> fix(orchestrator): compute args_output in add_node/collator

- crates/orchestrator/src/errors.rs
- crates/orchestrator/src/generators/command.rs
- crates/orchestrator/src/generators/errors.rs
- crates/orchestrator/src/generators/para_artifact.rs
- crates/orchestrator/src/network.rs
- crates/orchestrator/src/network/node.rs
- crates/orchestrator/src/network/parachain.rs
- crates/orchestrator/src/network/relaychain.rs
- crates/orchestrator/src/network_spec/node.rs
Firstly, thank you for an amazing library! The original zombienet is a Polkadot staple and now being able to use it completely from Rust is a game changer for us: as you may be aware, we have integrated zombienet-sdk with [pop-cli](https://github.com/paritytech/zombienet-sdk).
In doing so, we needed to add a few getters to the public api to be able to present certain information to the user, as well we expose a little more of the inner errors. This PR simply upstreams these changes.
It also includes two additional fixes, which may be better implemented based on your guidance:
- collator args werent working for us when specified in a config file, which seemed to be due to missing `--` in the args list provided by calling functions. 
- artifact path wasnt set when trying to build a chain …
> feat: enhance public api

- crates/provider/src/docker/client.rs
- crates/provider/src/docker/namespace.rs
- crates/provider/src/docker/provider.rs
- crates/provider/src/kubernetes/namespace.rs
- crates/provider/src/lib.rs
fix #214 
- Fix docker leaking containers
- Also fix docker download helpers
- Improve docker rm _namespaced_ containers
cc: @michalkucharczyk
> fix(docker): don't leak containers on ctrl+c

- crates/orchestrator/src/generators/chain_spec.rs
> fix: Add warn when a raw chain-spec is provided

- crates/orchestrator/src/network/node.rs
- crates/sdk/tests/smoke.rs
- Add methods to `NetworkNode`
-  `wait_metric`  wait until the predicate fn pass
-   `wait_metric_with_timeout`  wait until the predicate fn pass with `timeout`
> feat(orchestrator): add wait_ methods for metrics assertions

- crates/sdk/src/environment.rs
- crates/sdk/src/lib.rs
- crates/sdk/tests/smoke.rs
Add environment helpers
example
```rs
...
let spawn_fn = get_spawn_fn();
let mut network = spawn_fn(config).await?;
```
Env vars used:
`ZOMBIE_PROVIDER`: could be `k8s`, `native`, `docker` (default)
Also, includes a helper to read the `images` from env
`get_images_from_env` use: 
`POLKADOT_IMAGE`:(docker.io/parity/polkadot:latest)
`CUMULUS_IMAGE`:(docker.io/parity/polkadot-parachain:latest)
Thx!
> feat: add environment helper

- crates/orchestrator/Cargo.toml
- crates/orchestrator/src/generators/chain_spec.rs
- crates/orchestrator/src/lib.rs
- crates/orchestrator/src/network_helper.rs
- crates/orchestrator/src/network_helper/metrics.rs
- crates/orchestrator/src/network_helper/verifier.rs
- crates/orchestrator/src/network_spec.rs
- crates/orchestrator/src/network_spec/parachain.rs
- crates/orchestrator/src/network_spec/relaychain.rs
- crates/orchestrator/src/shared/types.rs
- crates/provider/src/native/node.rs
Change exports.
@rzadp @Bullrich
> refactor to support zombie-bite

- crates/orchestrator/src/generators/chain_spec.rs
- crates/orchestrator/src/generators/keystore.rs
- crates/orchestrator/src/spawner.rs
When testing `zombienet-sdk` with cross-chain calls with Asset Hub, we found that the hrmp channels passed to the chainspec caused the following issue:
`Error: "Invalid JSON blob: invalid type: map, expected a tuple of size 4 at line 1 column 2794"`
This is because the values of `HrmpChannelConfig` serialise to a map instead of a tuple, as expected by https://github.com/paritytech/polkadot-sdk/blob/fc906d5d0fb7796ef54ba670101cf37b0aad6794/polkadot/runtime/parachains/src/hrmp.rs#L492. Tests were updated accordingly to facilitate this fix.
Additional commits were also added to enable some of Asset Hub on Polkadot functionality observed in the classic Zombienet repo, so that we are able to launch a local Polkadot network with Asset Hub should anyone require. Example configuration files can …
> fix(chain-spec): adjust hrmp channels json structure

- crates/orchestrator/src/generators/chain_spec.rs
- crates/orchestrator/src/lib.rs
- crates/orchestrator/src/network_spec.rs
- crates/orchestrator/src/network_spec/parachain.rs
- crates/provider/src/docker/node.rs
- crates/provider/src/kubernetes/node.rs
- crates/provider/src/lib.rs
- crates/provider/src/native/node.rs
- Add binaries verification to `validate_spec_with_provider_capabilities`
- Improve error display in providers.
> add check for binaries in native

- crates/orchestrator/src/lib.rs
- crates/orchestrator/src/network/node.rs
- crates/support/src/net.rs
Fixes:
- `wait` methods for metrics
- `path` checking for `native` provider validation.
> Fix wait on metrics and path checking

- Cargo.toml
- Fixes:
- `wait` metrics
- `validation` for binaries (native provider).
> bump versions for release `v0.2.9`

- crates/orchestrator/src/network/node.rs
This is nothing big  :) 
The code execution logic is already present under `pjs` function, yet it is duplicated for `pjs_file` function. 
This change re-uses the existing code, so that you won't have to change it twice in the future.
> reuse pjs code execution code

- crates/configuration/src/parachain.rs
- crates/configuration/testing/snapshots/0003-small-network_w_parachain.toml
`v1` version support define a parachain with a single collator using `[parachain.collator]` (note this is a map and not a sequence). But in the `sdk` we drop support in favor of always use a vec<NodeConfig>. This pr allow to use the old toml definition __only__ with the load_from_toml method.
cc:  @AlexD10S
> support single collator config in `toml`

- Cargo.toml
- crates/configuration/src/parachain.rs
- crates/configuration/src/utils.rs
- crates/configuration/testing/snapshots/0001-big-network.toml
- crates/configuration/testing/snapshots/0002-overridden-defaults.toml
- crates/configuration/testing/snapshots/0003-small-network_w_parachain.toml
- crates/orchestrator/Cargo.toml
- crates/orchestrator/src/generators/chain_spec.rs
- crates/orchestrator/src/generators/key.rs
- crates/orchestrator/src/network_spec.rs
- crates/orchestrator/src/network_spec/parachain.rs
- Fix stash derivation (use `//`)
- Add `evm` support, you can set your parachain as evm based with `evm_based(choice: bool)`.
Fix: #247 
cc: @AlexD10S / @al3mart
> add support for evm and fix stash account

- Cargo.toml
- Fixes: 
- Use correct stash account
-  Support single collator in `toml` (load from file)
- Added
- Add support for `evm` parachains, through the `evm_based` config (both in load from toml and builder).
> bump version for release `0.2.10`

- crates/configuration/Cargo.toml
- crates/configuration/src/shared/types.rs
- crates/orchestrator/src/lib.rs
- crates/orchestrator/src/network/node.rs
- crates/orchestrator/src/network/relaychain.rs
- crates/orchestrator/src/shared/types.rs
- crates/orchestrator/src/tx_helper.rs
- crates/orchestrator/src/tx_helper/runtime_upgrade.rs
- crates/sdk/src/lib.rs
Added:
- Helper to perform a runtime upgrade on the relaychain
```rust
let wasm = "file_path__or__url_to_*.compact.compressed.wasm";
network
.relaychain()
.runtime_upgrade(RuntimeUpgradeOptions::new(wasm.into()))
.await?;
```
> add runtime_upgrade for releaychain

- Cargo.toml
Added
- Runtime upgrade helper for relaychain.
> bump versions for release `v0.2.11`

- crates/configuration/src/shared/errors.rs
- crates/configuration/src/shared/helpers.rs
- crates/configuration/src/shared/node.rs
Add: 
- Validate `node_name`, can't be empty
cc: @ozgunozerk
> add validation to node name, can't be empty

- Cargo.toml
Fix:
- Grandpa keys injected. #267
Added:
- Name validation (for nodes) #266
- Improve dx (@ozgunozerk ) #261
> bump versions `0.2.14`

- Cargo.toml
As stated in the title.
The fact that zombienet-sdk depends on subxt 0.37 was making my project complain that the Config that I had didn't implement the Config required by `wait_client`.
Please cut a new release along with this 🙏
> Upgrade subxt to 0.38

- crates/orchestrator/src/generators/chain_spec.rs
fix for https://github.com/paritytech/polkadot-sdk/issues/6575
cc: @iulianbarbu
> Override keys iff they are present

- .github/workflows/ci.yml
- Cargo.toml
- crates/configuration/Cargo.toml
- crates/configuration/src/network.rs
- crates/configuration/src/parachain.rs
- crates/configuration/src/relaychain.rs
- crates/orchestrator/Cargo.toml
- crates/orchestrator/src/generators/chain_spec.rs
- crates/orchestrator/src/network/node.rs
- crates/sdk/Cargo.toml
Add logic to allow overrides working with network definition in `toml` format and sdk api.
cc: @iulianbarbu
> fix: override genesis to work with toml files/api

- crates/examples/examples/add_para.rs
- crates/examples/examples/para_upgrade.rs
- crates/examples/examples/pjs.rs
- crates/examples/examples/simple_network_example.rs
- crates/orchestrator/src/network/node.rs
- crates/orchestrator/src/tx_helper/runtime_upgrade.rs
- crates/sdk/tests/smoke.rs
Generally the idea is that `wait_client` should be used as a node can take a moment to appear online.
> Deprecate `client` function and replace with `try_client`

- crates/configuration/src/global_settings.rs
- crates/configuration/src/network.rs
- crates/configuration/src/utils.rs
- crates/configuration/testing/snapshots/0000-small-network.toml
- crates/configuration/testing/snapshots/0001-big-network.toml
- crates/configuration/testing/snapshots/0002-overridden-defaults.toml
- crates/configuration/testing/snapshots/0003-small-network_w_parachain.toml
- crates/configuration/testing/snapshots/0004-small-network-without-settings.toml
Fix #254 
Add logic to load `toml`s without `[settings]` (set defaults).
cc: @jmg-duarte
> fix: #254, allow toml without 'settings' (set defaults)

- crates/orchestrator/src/generators/chain_spec.rs
> return without percolating if top level key isn't part of the pointer

- crates/orchestrator/src/network/node.rs
- crates/provider/src/kubernetes/client.rs
- crates/provider/src/kubernetes/node.rs
- crates/provider/src/shared/scripts/zombie-wrapper.sh
- crates/sdk/tests/smoke.rs
cc: @ordian 
Fix resume/pause for k8s provider.
> fix(k8s) resume/pause

- Cargo.toml
- crates/examples/Cargo.toml
- crates/orchestrator/Cargo.toml
- crates/provider/Cargo.toml
- crates/sdk/Cargo.toml
Now, dependencies are aligned with polkadot-sdk, and Deno no longer blocks future dependency upgradation
> Upgrade pjs and reqwest

- crates/configuration/src/network.rs
- crates/configuration/src/parachain.rs
- crates/configuration/src/relaychain.rs
- crates/configuration/testing/snapshots/0005-small-networl-with-wasm-override.toml
- crates/orchestrator/src/generators/chain_spec.rs
- crates/orchestrator/src/generators/errors.rs
- crates/orchestrator/src/lib.rs
- crates/orchestrator/src/network_spec/parachain.rs
- crates/orchestrator/src/network_spec/relaychain.rs
Add `with_wasm_override` fn to both `relaychain` and `parachain` builders.
cc: @ggwpez
> add option to override `wasm` in chain-spec

- crates/provider/src/kubernetes/pod_spec_builder.rs
- crates/provider/src/shared/scripts/helper-binaries-downloader.sh
Fix `ci` issues where we get error download bins from gh.
> [CI] use our init image to get the bins

- crates/orchestrator/src/lib.rs
- crates/orchestrator/src/network.rs
- crates/orchestrator/src/network/node.rs
- crates/orchestrator/src/spawner.rs
- crates/support/Cargo.toml
- crates/support/src/replacer.rs
Add support for context (from runtime network replacements) as we have in v1.
__Migration path__:
Instead of using the v1 filters (from nunjucks)
```
{{'alice'|zombie('multiAddress')}}
```
you need to use the direct form that v1 use behind the filer of
```
{{ZOMBIE:alice:multiAddress}}
```
In the form 
```
{{ZOMBIE:<node name>:<node field>
```
Available fields are:
- multiAddres / multiaddr
- wsUri / ws_uri
- prometheusUri / prometheus_uri
- name
cc: @lrubasze
> implement context replacement

- crates/orchestrator/src/generators/chain_spec.rs
Only clear `validatorCount` IFF staking is set but __not__ `devStakers`.
cc: @tdimitrov
> add logic to handle `devStakers` key without override the validator count

- crates/orchestrator/Cargo.toml
- crates/orchestrator/src/network/node.rs
This PR improves log parsing by introducing some changes `wait_log_line_count_with_timeout()`.
The method searches log lines for a given substring or glob pattern,
and evaluates the number of matching lines using a user-provided predicate function.
Optionally, it can wait for the full timeout duration to ensure the condition
holds consistently (e.g., for verifying absence of logs).
It uses `LogLineCountOptions` struct to configure the timeout, match count predicate and full-duration waiting.
It returns enum `LogLineCount`:
* `Ok(LogLineCount::TargetReached(n))` if the predicate was satisfied within the timeout,
* `Ok(LogLineCount::TargetFails(n))` if the predicate was not satisfied in time,
* `Err(e)` if an error occurred during log retrieval or matching.
Additionally added some tests to …
> Log lines parsing improvements

- crates/configuration/src/shared/types.rs
- crates/orchestrator/src/generators/command.rs
- crates/orchestrator/src/generators/para_artifact.rs
- crates/orchestrator/src/lib.rs
- crates/orchestrator/src/network/node.rs
- crates/orchestrator/src/spawner.rs
Changes:
- Add array variant for `Arg` type
This is useful for parameters, which might accept multiple values, eg.
"--bootnodes", "--relay-chain-rpc-url"
Example:
```
--relay-chain-rpc-url ws://127.0.0.1:65168 ws://127.0.0.1:65170  ws://127.0.0.1:65172 
```
Also added some tests for serialize/deserialize `Arg` type.
Additional changes:
- Always calculate `multiaddr` for spawned node
Some tests expected multiaddr to be available, but it was None. Having `multiaddrs` in node's context does not harm :)
> Support multiple args

- crates/cli/src/main.rs
- crates/configuration/src/global_settings.rs
- crates/orchestrator/Cargo.toml
- crates/orchestrator/src/generators/chain_spec.rs
- crates/orchestrator/src/generators/para_artifact.rs
- crates/orchestrator/src/lib.rs
- crates/orchestrator/src/network_spec.rs
- crates/orchestrator/src/network_spec/parachain.rs
- crates/orchestrator/src/network_spec/relaychain.rs
- crates/support/src/replacer.rs
Allow to set the concurrency for spawn nodes. _If_ we detect some reference between the nodes (using the `ZOMBIE:` token we override the concurrency to 1. 
Also, the concurrency can be set using this env var `ZOMBIE_SPAWN_CONCURRENCY` that take precedence over the config.
cc: @lrubasze
> feat, allow spawn seq.

- crates/cli/src/main.rs
- crates/cli/testing/config.toml
- crates/provider/src/native/namespace.rs
Add `-d` and `-c` options
```
Usage: zombie-cli spawn [OPTIONS] <CONFIG>
Arguments:
<CONFIG>
Options:
-p, --provider <PROVIDER>
[default: docker] [possible values: docker, k8s, native]
-d, --dir <BASE_PATH>
Directory path for placing the network files instead of random temp one (e.g. -d /home/user/my-zombienet)
-c, --spawn-concurrency <SPAWN_CONCURRENCY>
Number of concurrent spawning process to launch
-h, --help
Print help
```
> add support for base_path/concurrency in cli

- crates/configuration/src/network.rs
- crates/configuration/src/parachain.rs
- crates/configuration/src/relaychain.rs
- crates/configuration/src/shared/node.rs
- crates/examples/examples/0002-simple-group-nodes.toml
- crates/examples/examples/add_para.rs
- crates/examples/examples/big_network_with_group_nodes.rs
- crates/examples/examples/network_example_with_group_nodes.rs
- crates/orchestrator/src/network_spec/parachain.rs
- crates/orchestrator/src/network_spec/relaychain.rs
Implements #401 
Add support for grouping nodes with shared configuration
Implemented for both relaychain and parachain nodes.
Example: 
```toml
[relaychain]
[[relaychain.node_groups]]
name = "group1"
image = "docker.io/parity/polkadot:latest"
command = "polkadot"
validator = true
count = 3
[[relaychain.node_groups]]
name = "group2"
image = "docker.io/parity/polkadot:latest"
command = "polkadot"
validator = true
count = 2
[[relaychain.nodes]]
name = "alice"
args = [ "--alice", "-lruntime=debug,parachain=trace" ]
[[parachains]]
id = 100
addToGenesis = false
cumulus_based = false
[[parachains.collators]]
name = "collator01"
image = "{{COL_IMAGE}}"
command = "adder-collator"
args = [ "-lruntime=debug,parachain=trace" ]
[[parachains.collator_groups]]
name = "collator_group"
image = …
```
> Node groups support

- crates/configuration/src/network.rs
Fixes warnings from https://github.com/paritytech/zombienet-sdk/actions/runs/18093770042/job/51480211346 (Use of deprecated method)
> Fix warnings
